spring.datasource.url=jdbc:postgresql://localhost:5432/tgbotdb
spring.datasource.username=tgbotadmin
spring.datasource.password=tgbotadmin
telegram.bot.token=8142365765:AAHZDmq7EtCKZJrv-MtMUNSihIPhWRNXvtU
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
